cp shop_users.php ../../../shop_users.php
cp shop_users_edit.php ../../../shop_users_edit.php
cp shop_users_view.php ../../../shop_users_view.php
cp admin/admin_user_shops.php ../../../admin/admin_user_shops.php
cp images/icon_user_shop.gif ../../../templates/subSilver/images/icon_user_shop.gif
cp images/icon_user_shop.gif ../../../templates/guildwars_tree/images/icon_user_shop.gif
cp images/icon_user_shop.gif ../../../templates/Elveron/images/icon_user_shop.gif
cp templates/shop/shop_users_body.tpl ../../../templates/subSilver/shop/shop_users_body.tpl
cp templates/shop/shop_users_body.tpl ../../../templates/guildwars_tree/shop/shop_users_body.tpl
cp templates/shop/shop_users_body.tpl ../../../templates/Elveron/shop/shop_users_body.tpl
cp templates/shop/shop_users_config.tpl ../../../templates/subSilver/shop/shop_users_config.tpl
cp templates/shop/shop_users_config.tpl ../../../templates/guildwars_tree/shop/shop_users_config.tpl
cp templates/shop/shop_users_config.tpl ../../../templates/Elveron/shop/shop_users_config.tpl
cp templates/shop/shop_users_view.tpl ../../../templates/subSilver/shop/shop_users_view.tpl
cp templates/shop/shop_users_view.tpl ../../../templates/guildwars_tree/shop/shop_users_view.tpl
cp templates/shop/shop_users_view.tpl ../../../templates/Elveron/shop/shop_users_view.tpl
cp templates/admin/user_shops_body.tpl ../../../templates/subSilver/admin/user_shops_body.tpl
cp templates/admin/user_shops_body.tpl ../../../templates/guildwars_tree/admin/user_shops_body.tpl
cp templates/admin/user_shops_body.tpl ../../../templates/Elveron/admin/user_shops_body.tpl
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_english/lang_shop.php backups/language/lang_english/lang_shop.php.txt
cp processed/language/lang_english/lang_shop.php.txt ../../../language/lang_english/lang_shop.php
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/guildwars_tree/overall_header.tpl backups/templates/guildwars_tree/overall_header.tpl.txt
cp processed/templates/guildwars_tree/overall_header.tpl.txt ../../../templates/guildwars_tree/overall_header.tpl
cp ../../../templates/Elveron/overall_header.tpl backups/templates/Elveron/overall_header.tpl.txt
cp processed/templates/Elveron/overall_header.tpl.txt ../../../templates/Elveron/overall_header.tpl
