cp root/admin/admin_prune_users.php ../../../admin/admin_prune_users.php
cp root/templates/subSilver/admin/prune_users.tpl ../../../templates/subSilver/admin/prune_users.tpl
cp root/templates/subSilver/admin/prune_users.tpl ../../../templates/guildwars_tree/admin/prune_users.tpl
cp root/templates/subSilver/admin/prune_users.tpl ../../../templates/Elveron/admin/prune_users.tpl
cp root/templates/subSilver/admin/prune_users.tpl ../../../templates/xhtml_guildwars/admin/prune_users.tpl
cp root/templates/subSilver/admin/prune_users_sql.tpl ../../../templates/subSilver/admin/prune_users_sql.tpl
cp root/templates/subSilver/admin/prune_users_sql.tpl ../../../templates/guildwars_tree/admin/prune_users_sql.tpl
cp root/templates/subSilver/admin/prune_users_sql.tpl ../../../templates/Elveron/admin/prune_users_sql.tpl
cp root/templates/subSilver/admin/prune_users_sql.tpl ../../../templates/xhtml_guildwars/admin/prune_users_sql.tpl
cp root/templates/subSilver/admin/prune_users_list.tpl ../../../templates/subSilver/admin/prune_users_list.tpl
cp root/templates/subSilver/admin/prune_users_list.tpl ../../../templates/guildwars_tree/admin/prune_users_list.tpl
cp root/templates/subSilver/admin/prune_users_list.tpl ../../../templates/Elveron/admin/prune_users_list.tpl
cp root/templates/subSilver/admin/prune_users_list.tpl ../../../templates/xhtml_guildwars/admin/prune_users_list.tpl
cp root/templates/subSilver/images/user_flag.gif ../../../templates/subSilver/images/user_flag.gif
cp root/templates/subSilver/images/user_flag.gif ../../../templates/guildwars_tree/images/user_flag.gif
cp root/templates/subSilver/images/user_flag.gif ../../../templates/Elveron/images/user_flag.gif
cp root/templates/subSilver/images/user_flag.gif ../../../templates/xhtml_guildwars/images/user_flag.gif
cp root/templates/subSilver/images/user_unflag.gif ../../../templates/subSilver/images/user_unflag.gif
cp root/templates/subSilver/images/user_unflag.gif ../../../templates/guildwars_tree/images/user_unflag.gif
cp root/templates/subSilver/images/user_unflag.gif ../../../templates/Elveron/images/user_unflag.gif
cp root/templates/subSilver/images/user_unflag.gif ../../../templates/xhtml_guildwars/images/user_unflag.gif
cp root/templates/sort.js ../../../templates/sort.js
cp root/language/lang_english/email/user_inactive_notify.tpl ../../../language/lang_english/email/user_inactive_notify.tpl
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
