cp ../../../includes/bbcode.php backups/includes/bbcode.php.txt
cp processed/includes/bbcode.php.txt ../../../includes/bbcode.php
cp ../../../templates/subSilver/bbcode.tpl backups/templates/subSilver/bbcode.tpl.txt
cp processed/templates/subSilver/bbcode.tpl.txt ../../../templates/subSilver/bbcode.tpl
cp ../../../templates/guildwars_tree/bbcode.tpl backups/templates/guildwars_tree/bbcode.tpl.txt
cp processed/templates/guildwars_tree/bbcode.tpl.txt ../../../templates/guildwars_tree/bbcode.tpl
cp ../../../templates/Elveron/bbcode.tpl backups/templates/Elveron/bbcode.tpl.txt
cp processed/templates/Elveron/bbcode.tpl.txt ../../../templates/Elveron/bbcode.tpl
cp ../../../templates/xhtml_guildwars/bbcode.tpl backups/templates/xhtml_guildwars/bbcode.tpl.txt
cp processed/templates/xhtml_guildwars/bbcode.tpl.txt ../../../templates/xhtml_guildwars/bbcode.tpl
cp ../../../templates/subSilver/posting_body.tpl backups/templates/subSilver/posting_body.tpl.txt
cp processed/templates/subSilver/posting_body.tpl.txt ../../../templates/subSilver/posting_body.tpl
cp ../../../templates/guildwars_tree/posting_body.tpl backups/templates/guildwars_tree/posting_body.tpl.txt
cp processed/templates/guildwars_tree/posting_body.tpl.txt ../../../templates/guildwars_tree/posting_body.tpl
cp ../../../templates/Elveron/posting_body.tpl backups/templates/Elveron/posting_body.tpl.txt
cp processed/templates/Elveron/posting_body.tpl.txt ../../../templates/Elveron/posting_body.tpl
cp ../../../templates/xhtml_guildwars/posting_body.tpl backups/templates/xhtml_guildwars/posting_body.tpl.txt
cp processed/templates/xhtml_guildwars/posting_body.tpl.txt ../../../templates/xhtml_guildwars/posting_body.tpl
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
