cp scratch_card.php ../../../shop/scratch_card.php
cp images/scratch/blank.gif ../../../shop/images/scratch/blank.gif
cp images/scratch/finish_box.gif ../../../shop/images/scratch/finish_box.gif
cp images/scratch/icon_1.gif ../../../shop/images/scratch/icon_1.gif
cp images/scratch/icon_2.gif ../../../shop/images/scratch/icon_2.gif
cp images/scratch/icon_3.gif ../../../shop/images/scratch/icon_3.gif
cp images/scratch/icon_4.gif ../../../shop/images/scratch/icon_4.gif
cp images/scratch/icon_5.gif ../../../shop/images/scratch/icon_5.gif
cp images/scratch/scratch_card.jpg ../../../shop/images/scratch/blank.gif
cp images/scratch/scratched.gif ../../../shop/images/scratch/scratched.gif
cp templates/shop/item_scratch_card.tpl ../../../templates/subSilver/shop/item_scratch_card.tpl
cp templates/shop/item_scratch_card.tpl ../../../templates/guildwars_tree/shop/item_scratch_card.tpl
cp templates/shop/item_scratch_card.tpl ../../../templates/Elveron/shop/item_scratch_card.tpl
cp ../../../admin/admin_shop.php backups/admin/admin_shop.php.txt
cp processed/admin/admin_shop.php.txt ../../../admin/admin_shop.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../language/lang_english/lang_shop.php backups/language/lang_english/lang_shop.php.txt
cp processed/language/lang_english/lang_shop.php.txt ../../../language/lang_english/lang_shop.php
cp ../../../shop_bs.php backups/shop_bs.php.txt
cp processed/shop_bs.php.txt ../../../shop_bs.php
