cp shop.php ../../../shop.php
cp shop_actions.php ../../../shop_actions.php
cp shop_bs.php ../../../shop_bs.php
cp shop_inventory.php ../../../shop_inventory.php
cp admin/admin_shop.php ../../../admin/admin_shop.php
cp language/lang_english/lang_shop.php ../../../language/lang_english/lang_shop.php
cp templates/admin/shop_config_body.tpl ../../../templates/subSilver/admin/shop_config_body.tpl
cp templates/admin/shop_config_body.tpl ../../../templates/guildwars_tree/admin/shop_config_body.tpl
cp templates/admin/shop_config_body.tpl ../../../templates/Elveron/admin/shop_config_body.tpl
cp templates/admin/shop_edit_item.tpl ../../../templates/subSilver/admin/shop_edit_item.tpl
cp templates/admin/shop_edit_item.tpl ../../../templates/guildwars_tree/admin/shop_edit_item.tpl
cp templates/admin/shop_edit_item.tpl ../../../templates/Elveron/admin/shop_edit_item.tpl
cp templates/admin/shop_edit_shop.tpl ../../../templates/subSilver/admin/shop_edit_shop.tpl
cp templates/admin/shop_edit_shop.tpl ../../../templates/guildwars_tree/admin/shop_edit_shop.tpl
cp templates/admin/shop_edit_shop.tpl ../../../templates/Elveron/admin/shop_edit_shop.tpl
cp templates/admin/shop_edit_user.tpl ../../../templates/subSilver/admin/shop_edit_user.tpl
cp templates/admin/shop_edit_user.tpl ../../../templates/guildwars_tree/admin/shop_edit_user.tpl
cp templates/admin/shop_edit_user.tpl ../../../templates/Elveron/admin/shop_edit_user.tpl
cp templates/shop/shop_action_discard.tpl ../../../templates/subSilver/shop/shop_action_discard.tpl
cp templates/shop/shop_action_discard.tpl ../../../templates/guildwars_tree/shop/shop_action_discard.tpl
cp templates/shop/shop_action_discard.tpl ../../../templates/Elveron/shop/shop_action_discard.tpl
cp templates/shop/shop_action_give.tpl ../../../templates/subSilver/shop/shop_action_give.tpl
cp templates/shop/shop_action_give.tpl ../../../templates/guildwars_tree/shop/shop_action_give.tpl
cp templates/shop/shop_action_give.tpl ../../../templates/Elveron/shop/shop_action_give.tpl
cp templates/shop/shop_action_trade.tpl ../../../templates/subSilver/shop/shop_action_trade.tpl
cp templates/shop/shop_action_trade.tpl ../../../templates/guildwars_tree/shop/shop_action_trade.tpl
cp templates/shop/shop_action_trade.tpl ../../../templates/Elveron/shop/shop_action_trade.tpl
cp templates/shop/shop_buy.tpl ../../../templates/subSilver/shop/shop_buy.tpl
cp templates/shop/shop_buy.tpl ../../../templates/guildwars_tree/shop/shop_buy.tpl
cp templates/shop/shop_buy.tpl ../../../templates/Elveron/shop/shop_buy.tpl
cp templates/shop/shop_districts.tpl ../../../templates/subSilver/shop/shop_districts.tpl
cp templates/shop/shop_districts.tpl ../../../templates/guildwars_tree/shop/shop_districts.tpl
cp templates/shop/shop_districts.tpl ../../../templates/Elveron/shop/shop_districts.tpl
cp templates/shop/shop_inventory_body.tpl ../../../templates/subSilver/shop/shop_inventory_body.tpl
cp templates/shop/shop_inventory_body.tpl ../../../templates/guildwars_tree/shop/shop_inventory_body.tpl
cp templates/shop/shop_inventory_body.tpl ../../../templates/Elveron/shop/shop_inventory_body.tpl
cp templates/shop/shop_item_body.tpl ../../../templates/subSilver/shop/shop_item_body.tpl
cp templates/shop/shop_item_body.tpl ../../../templates/guildwars_tree/shop/shop_item_body.tpl
cp templates/shop/shop_item_body.tpl ../../../templates/Elveron/shop/shop_item_body.tpl
cp templates/shop/shop_list.tpl ../../../templates/subSilver/shop/shop_list.tpl
cp templates/shop/shop_list.tpl ../../../templates/guildwars_tree/shop/shop_list.tpl
cp templates/shop/shop_list.tpl ../../../templates/Elveron/shop/shop_list.tpl
cp templates/shop/shop_list_body.tpl ../../../templates/subSilver/shop/shop_list_body.tpl
cp templates/shop/shop_list_body.tpl ../../../templates/guildwars_tree/shop/shop_list_body.tpl
cp templates/shop/shop_list_body.tpl ../../../templates/Elveron/shop/shop_list_body.tpl
cp templates/shop/shop_sell.tpl ../../../templates/subSilver/shop/shop_sell.tpl
cp templates/shop/shop_sell.tpl ../../../templates/guildwars_tree/shop/shop_sell.tpl
cp templates/shop/shop_sell.tpl ../../../templates/Elveron/shop/shop_sell.tpl
cp images/icon_shop.gif ../../../templates/subSilver/images/icon_shop.gif
cp images/icon_shop.gif ../../../templates/guildwars_tree/images/icon_shop.gif
cp images/icon_shop.gif ../../../templates/Elveron/images/icon_shop.gif
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/guildwars_tree/overall_header.tpl backups/templates/guildwars_tree/overall_header.tpl.txt
cp processed/templates/guildwars_tree/overall_header.tpl.txt ../../../templates/guildwars_tree/overall_header.tpl
cp ../../../templates/Elveron/overall_header.tpl backups/templates/Elveron/overall_header.tpl.txt
cp processed/templates/Elveron/overall_header.tpl.txt ../../../templates/Elveron/overall_header.tpl
cp ../../../templates/subSilver/profile_view_body.tpl backups/templates/subSilver/profile_view_body.tpl.txt
cp processed/templates/subSilver/profile_view_body.tpl.txt ../../../templates/subSilver/profile_view_body.tpl
cp ../../../templates/guildwars_tree/profile_view_body.tpl backups/templates/guildwars_tree/profile_view_body.tpl.txt
cp processed/templates/guildwars_tree/profile_view_body.tpl.txt ../../../templates/guildwars_tree/profile_view_body.tpl
cp ../../../templates/Elveron/profile_view_body.tpl backups/templates/Elveron/profile_view_body.tpl.txt
cp processed/templates/Elveron/profile_view_body.tpl.txt ../../../templates/Elveron/profile_view_body.tpl
