cp ../../../groupcp.php backups/groupcp.php.txt
cp processed/groupcp.php.txt ../../../groupcp.php
cp ../../../memberlist.php backups/memberlist.php.txt
cp processed/memberlist.php.txt ../../../memberlist.php
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../admin/admin_board.php backups/admin/admin_board.php.txt
cp processed/admin/admin_board.php.txt ../../../admin/admin_board.php
cp ../../../admin/admin_users.php backups/admin/admin_users.php.txt
cp processed/admin/admin_users.php.txt ../../../admin/admin_users.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../includes/usercp_avatar.php backups/includes/usercp_avatar.php.txt
cp processed/includes/usercp_avatar.php.txt ../../../includes/usercp_avatar.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../includes/usercp_register.php backups/includes/usercp_register.php.txt
cp processed/includes/usercp_register.php.txt ../../../includes/usercp_register.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
