cp admin_itemfinder.php ../../../admin/admin_itemfinder.php
cp itemfinder_config_body.tpl ../../../template/subSilver/admin/itemfinder_config_body.tpl
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/guildwars_tree/overall_header.tpl backups/templates/guildwars_tree/overall_header.tpl.txt
cp processed/templates/guildwars_tree/overall_header.tpl.txt ../../../templates/guildwars_tree/overall_header.tpl
cp ../../../templates/Elveron/overall_header.tpl backups/templates/Elveron/overall_header.tpl.txt
cp processed/templates/Elveron/overall_header.tpl.txt ../../../templates/Elveron/overall_header.tpl
cp ../../../templates/xhtml_guildwars/overall_header.tpl backups/templates/xhtml_guildwars/overall_header.tpl.txt
cp processed/templates/xhtml_guildwars/overall_header.tpl.txt ../../../templates/xhtml_guildwars/overall_header.tpl
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
