cp pid.php ../../../pid.php
cp pid.tpl ../../../templates/subSilver/pid.tpl
cp pid.tpl ../../../templates/guildwars_tree/pid.tpl
cp pid.tpl ../../../templates/Elveron/pid.tpl
cp pid.tpl ../../../templates/xhtml_guildwars/pid.tpl
cp ../../../login.php backups/login.php.txt
cp processed/login.php.txt ../../../login.php
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../admin/admin_board.php backups/admin/admin_board.php.txt
cp processed/admin/admin_board.php.txt ../../../admin/admin_board.php
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../includes/usercp_register.php backups/includes/usercp_register.php.txt
cp processed/includes/usercp_register.php.txt ../../../includes/usercp_register.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../templates/subSilver/profile_add_body.tpl backups/templates/subSilver/profile_add_body.tpl.txt
cp processed/templates/subSilver/profile_add_body.tpl.txt ../../../templates/subSilver/profile_add_body.tpl
cp ../../../templates/guildwars_tree/profile_add_body.tpl backups/templates/guildwars_tree/profile_add_body.tpl.txt
cp processed/templates/guildwars_tree/profile_add_body.tpl.txt ../../../templates/guildwars_tree/profile_add_body.tpl
cp ../../../templates/Elveron/profile_add_body.tpl backups/templates/Elveron/profile_add_body.tpl.txt
cp processed/templates/Elveron/profile_add_body.tpl.txt ../../../templates/Elveron/profile_add_body.tpl
cp ../../../templates/xhtml_guildwars/profile_add_body.tpl backups/templates/xhtml_guildwars/profile_add_body.tpl.txt
cp processed/templates/xhtml_guildwars/profile_add_body.tpl.txt ../../../templates/xhtml_guildwars/profile_add_body.tpl
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/guildwars_tree/overall_header.tpl backups/templates/guildwars_tree/overall_header.tpl.txt
cp processed/templates/guildwars_tree/overall_header.tpl.txt ../../../templates/guildwars_tree/overall_header.tpl
cp ../../../templates/Elveron/overall_header.tpl backups/templates/Elveron/overall_header.tpl.txt
cp processed/templates/Elveron/overall_header.tpl.txt ../../../templates/Elveron/overall_header.tpl
cp ../../../templates/xhtml_guildwars/overall_header.tpl backups/templates/xhtml_guildwars/overall_header.tpl.txt
cp processed/templates/xhtml_guildwars/overall_header.tpl.txt ../../../templates/xhtml_guildwars/overall_header.tpl
cp ../../../templates/subSilver/admin/board_config_body.tpl backups/templates/subSilver/admin/board_config_body.tpl.txt
cp processed/templates/subSilver/admin/board_config_body.tpl.txt ../../../templates/subSilver/admin/board_config_body.tpl
cp ../../../templates/guildwars_tree/admin/board_config_body.tpl backups/templates/guildwars_tree/admin/board_config_body.tpl.txt
cp processed/templates/guildwars_tree/admin/board_config_body.tpl.txt ../../../templates/guildwars_tree/admin/board_config_body.tpl
cp ../../../templates/Elveron/admin/board_config_body.tpl backups/templates/Elveron/admin/board_config_body.tpl.txt
cp processed/templates/Elveron/admin/board_config_body.tpl.txt ../../../templates/Elveron/admin/board_config_body.tpl
cp ../../../templates/xhtml_guildwars/admin/board_config_body.tpl backups/templates/xhtml_guildwars/admin/board_config_body.tpl.txt
cp processed/templates/xhtml_guildwars/admin/board_config_body.tpl.txt ../../../templates/xhtml_guildwars/admin/board_config_body.tpl
