cp shop_auctions.php ../../../shop_auctions.php
cp images/icon_auctions.gif ../../../templates/subSilver/images/icon_auctions.gif
cp images/icon_auctions.gif ../../../templates/guildwars_tree/images/icon_auctions.gif
cp images/icon_auctions.gif ../../../templates/Elveron/images/icon_auctions.gif
cp templates/auction_add.tpl ../../../templates/subSilver/auction_add.tpl
cp templates/auction_add.tpl ../../../templates/guildwars_tree/auction_add.tpl
cp templates/auction_add.tpl ../../../templates/Elveron/auction_add.tpl
cp templates/auction_body.tpl ../../../templates/subSilver/auction_body.tpl
cp templates/auction_body.tpl ../../../templates/guildwars_tree/auction_body.tpl
cp templates/auction_body.tpl ../../../templates/Elveron/auction_body.tpl
cp templates/auction_view.tpl ../../../templates/subSilver/auction_view.tpl
cp templates/auction_view.tpl ../../../templates/guildwars_tree/auction_view.tpl
cp templates/auction_view.tpl ../../../templates/Elveron/auction_view.tpl
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/guildwars_tree/overall_header.tpl backups/templates/guildwars_tree/overall_header.tpl.txt
cp processed/templates/guildwars_tree/overall_header.tpl.txt ../../../templates/guildwars_tree/overall_header.tpl
cp ../../../templates/Elveron/overall_header.tpl backups/templates/Elveron/overall_header.tpl.txt
cp processed/templates/Elveron/overall_header.tpl.txt ../../../templates/Elveron/overall_header.tpl
cp ../../../templates/subSilver/profile_view_body.tpl backups/templates/subSilver/profile_view_body.tpl.txt
cp processed/templates/subSilver/profile_view_body.tpl.txt ../../../templates/subSilver/profile_view_body.tpl
cp ../../../templates/guildwars_tree/profile_view_body.tpl backups/templates/guildwars_tree/profile_view_body.tpl.txt
cp processed/templates/guildwars_tree/profile_view_body.tpl.txt ../../../templates/guildwars_tree/profile_view_body.tpl
cp ../../../templates/Elveron/profile_view_body.tpl backups/templates/Elveron/profile_view_body.tpl.txt
cp processed/templates/Elveron/profile_view_body.tpl.txt ../../../templates/Elveron/profile_view_body.tpl
